runtime: custom
env: flex

instance_class: F4
automatic_scaling:
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  ASPNETCORE_URLS: 'http://*:8080'
  ASPNETCORE_ENVIRONMENT: 'Development'

skip_files:
  - ^bin/.*$
  - ^obj/.*$